### ISSUE TITLE
OneShot method doesn't call onDraw();

### ISSUE THREAD

**Issue by stevenfredian** [plattysoft/Leonids#103]
Anyone has idea why OneShot method doesn't call onDraw(); ?
But when i use Emitter example, onDraw called and display the particles...

I've used dispatchDraw, but it still has no particles displayed ...
(*Only happened on some devices)

**Comment by plattysoft** [comment]
I'm quite sure it does work. Can you share the code on how you're seeing it up?

There are examples for oneShot on the samples project

**Comment by stevenfredian** [comment]
Hi @plattysoft thanks for reply.
After check Developer Options...there are some configs that toggled off.
Window animation scale, Transition animation scale, and Animator duration scale.

thanks for response... i'll close this issue.
