### ISSUE TITLE
Gradle build file

### ISSUE THREAD

**Issue by jitpack** [plattysoft/Leonids#11]
Hi,

Would be really great to have gradle build file for Leonids. With that in place it becomes very easy to download it via https://jitpack.io

**Comment by plattysoft** [comment]
I think I uploaded it to jcentral already, but haven't tried if it works. Will check this weekend

**Comment by Reedyuk** [comment]
Second this, i think you havent uploaded it properly to jcenter, as you dumped the jar file, whereas it needs to be uploaded with a gradle file

**Comment by DanielMartinus** [comment]
@Reedyuk You are able to create a free project and versions at bintray.com and upload the following files:

application-name**.javadoc.jar**
application-name.**-javadoc.jar.md5**
application-name.**aar**
application-name.**aar.md5**
application-name.**jar** 
application-name.**jar.md5** 
application-name.**pom** 
application-name.**pom.md5**

I create these files for my SDK with: *./gradleW generateRelease* 

It would make it a lot easier for us to use the library :+1:

**Comment by plattysoft** [comment]
Apparently I am missing something since I did upload the jar file to bintray.com, but I did it via the web interface and it does not work when I try to use it via gradle.

I'll do an import of the whole project into Android Studio to get the file hierarchy and the gradle files and then update it here.

Yes, I do think that having the library on jcenter is important

**Comment by jitpack-io** [comment]
The missing part is probably a maven pom file.

In the meantime its also possible to install Leonids using Gradle from: https://jitpack.io/#plattysoft/Leonids

**Comment by plattysoft** [comment]
I uploaded an updated file structure with gradle files.

**Comment by plattysoft** [comment]
@jitpack you were right, I was missing the pom. Thanks.

I'm configuring gradle to do the automatic uploading to bintray now. I hope to have it done today.
