### ISSUE TITLE
Fix for emit gravity

### ISSUE THREAD

**Issue by andriistakhov** [plattysoft/Leonids#13]
Hi,

Please change in ParticleSystem#configureEmiter code from

line 457 mEmiterYMax = location[1] + emiter.getWidth() - mParentLocation[1];

to 

line 457 mEmiterYMax = location[1] + emiter.getHeight() - mParentLocation[1];

**Comment by plattysoft** [comment]
Thanks for the heads up, I'll be publishing an updated version soon. For now, this is fixed on the latest code.
