### ISSUE TITLE
Animation effect like below?

### ISSUE THREAD

**Issue by achinverma** [plattysoft/Leonids#16]
I want to create a animation with some dots and they are falling from top to bottom. For that I am using a translate animation which moves the dots images from top to bottom. But I want this to be continuous meaning the animation should repeat itself.

I have to create a animation with some dots and they are falling from top to bottom i will post gif animation  file , which is my requirement , please anyone guide me how to create this one?
it starts with FadeIn animation it is running fine in my code  and then the dots moving in continuous Motion from TOP TO BOTTOM as in gif i have posted it is not working in my code i have created 14 Linearlayouts they contains 7 texviews Horizontally with VISIBILITY.GONE in Oncreate i am changing its VISIBILITY to VISIBLE and starting FADE IN animation  and  i will post my code , please anyone guide me? 
![splash gif](https://cloud.githubusercontent.com/assets/2811593/6410268/e629f562-be93-11e4-85ae-cfddb19d7c0c.gif)
http://stackoverflow.com/questions/28762408/android-how-to-create-rain-like-animtion

**Comment by plattysoft** [comment]
This does not look like a particle system to me, but more like a parallax.

This is extremely regular and periodic. All the items of the image are using the same direction, speed and size. That makes it not a good fit for a particle system.

**Comment by achinverma** [comment]
do you have any example  for this, because i have created this with TranslationAnimation but it is not repeating.?

**Comment by plattysoft** [comment]
You should look for a parallax implementation, otherwise you'd need to do it yourself inside the onDraw method.

It is not hard to do, but it is a very particular case that I think you'd have to implement it yourself.
