### ISSUE TITLE
Particle always start from the Top Left point of the screen

### ISSUE THREAD

**Issue by hateum** [plattysoft/Leonids#18]
Thanks for this lib, it's really impressionnate.

I always have the particle emitted from the top-left point on the screen, how can I configure the particle system to make some particles float on the screen randomly.

**Comment by plattysoft** [comment]
Particles start from the center of the view they use as anchor. You can make them start from one of the sides or one of the corners by using emitWithGravity.

That being said, a particle system needs to have an emitting point (or line) once you know which one you want in your case, it should be easy to put a view in that position and make it work as you want

**Comment by hateum** [comment]
How can I make this ?
![example](https://cloud.githubusercontent.com/assets/1799019/6763917/6e0578e2-cf94-11e4-8bd0-33fca5ac6590.jpg)

**Comment by plattysoft** [comment]
That is a static image.

**Comment by hateum** [comment]
Sorry, I haven't an animated Gif, I have only this picture. 
The animation is : these masks float from the depth to the front and leaves the screen.
Can your library do this ?

**Comment by plattysoft** [comment]
As I said before: 

Are they spawning from a specific position (be it a point or a line)? Then yes.

Otherwise it could still be done but it won't be a particle system per se and you'd need to touch the code on the library itself.

**Comment by hateum** [comment]
No, they not spawning from a specific position, they do from random position.
Can you tell me what fonction I need to change ?

**Comment by plattysoft** [comment]
You can take a look at emitWithGravity to see how it gets spread over a line and make it a combination of the horizontal and vertical spreading so the particles get emitted from a square.
