### ISSUE TITLE
Taking Screenshot

### ISSUE THREAD

**Issue by emanuelthedude** [plattysoft/Leonids#23]
Hi,
I found your particle system and I like it a lot. Good work!!!
My problem is about screenshots. I wan't to programmatically take a screenshot while the particles are flying around on the screen. The problem is that the particles are missing on the screenshot.

I tried several solutions that I found on SO but none of them helped. 
http://stackoverflow.com/questions/2661536/how-to-programatically-take-a-screenshot-on-android
http://stackoverflow.com/questions/16748384/take-screenshot-programmatically-of-the-whole-screen

If I try it with the hardware buttons (power + volume-down) all particles are on the screenshot but I wan't to provide a screenshot button in the user interface. So I have to do it programmatically. The device has no root access.

Maybe you had the same problem and can give me a hint?

Best,
Emanuel

**Comment by plattysoft** [comment]
Interesting, never tried to make a screenshot programatically.

What the library does is (unless you provide an anchor view) is to add a view to the very parent view of the hierarchy, which is android.R.id.content.

My guess is that you are rendering a screenshot of a view that is lower in the hierarchy. Try using the anchor parameter to make the ParticleSystem be part of the view hierarchy of your app.

Anyway, what I usually do is to record a video and then take a snapshot from it.

Hope this works.

**Comment by emanuelthedude** [comment]
Hi,
thanks for your hint. I now use the topmost view and it works

I first call getRootView() on my layout to get the "real" RootView. It seems to be the same that you use for your particles.

    View topmostView = myRelativeLayout.getRootView()
 
When I want to take a screenshot I enable the drawingCache by

    topmostView.setDrawingCacheEnabled(true);

Now I can take a screenshot with particles. (This code is from SO)

    public static Bitmap takeScreenshot(View topmostView) {
        Bitmap bitmap = topmostView.getDrawingCache();
        Canvas canvas = new Canvas(bitmap);
        topmostView.draw(canvas);
        return bitmap;
    }

When I'm finished with screenshots I disable the drawingCache

    topmostView.setDrawingCacheEnabled(false);


It seems to work fine now
Thank you
