### ISSUE TITLE
Particles z-positioning not correct, help!

### ISSUE THREAD

**Issue by ynkm169** [plattysoft/Leonids#24]
I put particle view emitter under another view.
However, the particles are always showing on top of all other views, no matter what I do.

**Comment by ynkm169** [comment]
meah............
actually i just set parentViewId and its fine now.....gooooooooooooood

**Comment by plattysoft** [comment]
Yes, that is what the anchor view is for. Good that you found it yourself.

**Comment by salvonos** [comment]
I have same issue; How can set parentViewId?

**Comment by plattysoft** [comment]
parentViewId is the id of the view you want to be the parent of the ParticleSytem.

So it is whatever view you have set up in your hierarchy.
