### ISSUE TITLE
documents on initialization lacking

### ISSUE THREAD

**Issue by ynkm169** [plattysoft/Leonids#25]
the constructor 

new ParticleSystem 

should only be called after your view is loaded and positioned. Nothing is mentioned. Took me a while to find out.

If you do it inside activity construction, it will make emitter coordinates always 0,0
		int[] location = new int[2];
		emiter.getLocationInWindow(location);

**Comment by ynkm169** [comment]
i changed it to this and now it is working...

	@Override
	public void onWindowFocusChanged (boolean hasFocus) {
		ViewGroup button = (ViewGroup) findViewById(R.id.emitterParent);
		for (int i = 0; i < button.getChildCount(); i++) {
			new ParticleSystem(this, 1000, R.drawable.particlestar, 600, R.id.drawingBg)		
			.setSpeedByComponentsRange(-0.03f, 0.03f, -0.03f, 0.03f)
			.setAcceleration(0, 90) //0.000003f
			.setInitialRotationRange(0, 360)
			.setRotationSpeed(120)
			.setFadeOut(1300, new AccelerateInterpolator(3.0f))
			.addModifier(new ScaleModifier(0.6f, 1f, 0, 600))
			.emit(button.getChildAt(i), 50);
		}
		tableFppLayout.bringToFront();
	}

**Comment by plattysoft** [comment]
Yes, it is explained in the response to issue #22 and #21

Maybe it is a good idea to add it to the documentation.
