### ISSUE TITLE
Cannot set gravity TOP

### ISSUE THREAD

**Issue by ngochuu90** [plattysoft/Leonids#33]

**Comment by plattysoft** [comment]
can you be more specific about the problem, steps to replicate, code, expected result and actual result?

**Comment by ngochuu90** [comment]
Sorry. I have misunderstood the question. 
How to set Emit bottom to top ?
Thanks.

**Comment by plattysoft** [comment]
gravity is used to specify the place from which the particles emit from the view, it is used as "alignment", which is the meaning gravity has in Android layouting.

If you want particles to move upwards, then you need to set the speed to be negative on the y component.

Not sure if this was your question, but I hope you have a more clear understanding now.

**Comment by lsjwzh** [comment]
You can set Angle to 270
