### ISSUE TITLE
how to use it in Fragments

### ISSUE THREAD

**Issue by syedalinaqi** [plattysoft/Leonids#36]
i was trying to test it in an 'OnClick' method in a fragment but got an error...

new ParticleSystem(getActivity(), 80, R.drawable.error_center_x, 10000)
                        .setSpeedModuleAndAngleRange(0f, 0.3f, 180, 180)
                        .setRotationSpeed(144)
                        .setAcceleration(0.00005f, 90)
                        .emit(findViewById(R.id.emiter_top_right), 8);

and the Log

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference

**Comment by plattysoft** [comment]
This has been solved with #50
