### ISSUE TITLE
Laggy Performance

### ISSUE THREAD

**Issue by Jayvd** [plattysoft/Leonids#41]
This library is awesome but it is laggy, any ideas on performance improvements?

I tried the confetti example but the the lag is noticable(i.e.: not 60fps) 

Thank you

**Comment by plattysoft** [comment]
Since it is drawing on a canvas, the performance is not going to be great.
It is designed to be used in normal apps with standard views.
If you plan to use it intensively, you should probably use something that uses openGL, there are many of those.
