### ISSUE TITLE
oneShot method not working on some devices

### ISSUE THREAD

**Issue by CharlesGayot** [plattysoft/Leonids#45]
Hi,
Awesome and simple library, very nice job!
Everything is working fine in the emulator, but on my Xperia Z (running 5.1.1), the oneShot method doesn't work, both in the example APK and other custom code.
No error or debug info are displayed, however, I noticed some "normal extra" memory consumption when calling the method, it seems the drawable is loaded but not displayed.
No problem with the emit method.
Any idea?

**Comment by plattysoft** [comment]
Thanks for the heads up.

That's interesting. I have tested the library on a 5.1 device a while ago and it worked fine. I am not aware of any particularity of the Xperia Z, but I will look into it.

So, emit works but oneShot does not. The increased memory should be all the objects that are created (ParticleSystem, Particles, etc) but they are not shown.

I'll check the differences between one and the other and try to figure out the difference, maybe something that other phones do not require to run on the UI Thread. Not sure, but it should be relatively easy to spot.

**Comment by CharlesGayot** [comment]
Thanks for considering the problem, you got the essence of it :) 
Tell me if you need any testing!

**Comment by CharlesGayot** [comment]
I finally found the reason why the oneShot method was not working: the animations were deactivated on my phone; if I enable them then everything is working fine!
