### ISSUE TITLE
Wrong parameter type in setStartTime

### ISSUE THREAD

**Issue by ayltai** [plattysoft/Leonids#47]
`ParticleSystem.setStartTime(int)` ([ParticleSystem.java:375](https://github.com/plattysoft/Leonids/blob/5c9003393f4e148581a3c7cc2cfa5b713e926f84/LeonidsLib/src/main/java/com/plattysoft/leonids/ParticleSystem.java#L375)) requires an `int` parameter but what it really needs is a `long`.

**Comment by plattysoft** [comment]
Good point, thanks for the heads up.

I am having a few days (finally) to review and clean all the standing issues.
