### ISSUE TITLE
emmitWithGravity error. 

### ISSUE THREAD

**Issue by Barterio** [plattysoft/Leonids#53]
Hi, i'm using Leonids to create background raining animation.
The problem is that all particles are running from the top left corner one by one. Can you help me handle it?      

  ```
new ParticleSystem(MainActivity.this, 50, R.mipmap.ic_launcher, 5000)
                .setAcceleration(0.00013f, 90)
                .setSpeedByComponentsRange(0f, 0f, 0.05f, 0.1f)
                .setFadeOut(200, new AccelerateInterpolator())
                .emitWithGravity((Button)findViewById(R.id.mainForeground), Gravity.BOTTOM, 20);
```

**Comment by plattysoft** [comment]
The most likely problem is that you are starting the emitter inside onCreate or onStart.
At that moment, the views are not yet measured, therefore the system read the width of the view as 0.
You need to wait until the views are measured. Check out #22

**Comment by Barterio** [comment]
Thank you for your response!
I was thinking about this in that way, so thank you for your explanation answer!
