### ISSUE TITLE
Have other views appear on top of the particles?

### ISSUE THREAD

**Issue by Waro1234** [plattysoft/Leonids#65]
Well the is really all im asking. 

Is there current support of having views/layouts appear on top of the particles? Or will there ever be.

Greetings,
Waro

**Comment by plattysoft** [comment]
Yes, there is support for that, by default the Particle View is added to the content of the Activity and it is on the foreground, but there is a constructor that receives an id of a ViewGroup to be used as a parent.

Using that constructor you can put the particles at the level of depth you want in your app, you just need to define the anchor view.

**Comment by Waro1234** [comment]
i tried your solution but now the particles dont show up at all

**Comment by plattysoft** [comment]
Make sure that the anchor view covers all the screen and that no other view is obscuring it (i.e. a full screen View with a color)

A good tip is to make the anchor view to be of a solid background color and check if it is visible.

**Comment by Waro1234** [comment]
it's visible but the particles dont appear
