### ISSUE TITLE
question: is there a way to capture clicks on the falling objects

### ISSUE THREAD

**Issue by letitfly** [plattysoft/Leonids#86]
I am trying to rain gifts down from the sky and let the user click on the gift to claim it. The question is how to achieve that using ParticalSystem.

Thanks in advance!

**Comment by plattysoft** [comment]
Particles are designed so they are simple and the user does not interact with them, you want to create items that are interactive that are created in a similar -pseudo random- way as particles, but fundamentally they are not particles.

Take a look at the code of this other project to see somthing similar to what you want: https://github.com/plattysoft/BalloonsGame

Note: The project is a bit complex and uses an engine that I describe how to build on the book: [Mastering Andorid Game Development](https://www.amazon.com/Mastering-Android-Game-Development-Portales/dp/1783551771)

You can probably use the module as an engine and do the packets, but as I said, particles are not meant to be interactive.
