### ISSUE TITLE
Particles Translation animation lags.  

### ISSUE THREAD

**Issue by vishal21bhadani** [plattysoft/Leonids#93]
I am trying to do explosion animation. It's working fine but the particles moving animation(or translation) lags. It's not smooth.

**Comment by plattysoft** [comment]
As explained on the project description, this library is meant to be used on standard views, and therefore is drawing on a canvas.
There are inherent performance limitations when you draw on a canvas, which depend on the amount of particles you are drawing.
If you want smooth animations with many particles you need to use a proper rendering engine like OpenGL.
