### ISSUE TITLE
Project Build error

### ISSUE THREAD

**Issue by aboutgaurav** [plattysoft/Leonids#97]
I have successfully added the dependency for this library in my project.
When i try to run my application on device it shows this error.   

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/plattysoft/leonids/initializers/ParticleInitializer;

Library version : **1.3.2**
Support Library version : **26.1.0**

Thanks

**Comment by plattysoft** [comment]
it looks like you have added the project twice, or you have some of the files of the project also as source files.

**Comment by aboutgaurav** [comment]
Hey i cross checked  the dependencies and source files of the project and  couldn't find any ambiguity like mentioned above.



      dependencies {
      implementation 'com.android.support.constraint:constraint-layout:1.0.2'
      compile fileTree(include: ['*.jar'], dir: 'libs')
      androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
         exclude group: 'com.android.support', module: 'support-annotations'
      })

    //Generate multiple dalvik executable files
    implementation "com.android.support:multidex:$rootProject.multiDexVersion"

    //Android Support library
    implementation "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:support-v4:$rootProject.supportLibraryVersion"
    implementation "com.android.support:design:$rootProject.supportLibraryVersion"
    implementation "com.android.support:recyclerview-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:cardview-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:preference-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:palette-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:support-core-utils:$rootProject.supportLibraryVersion"


    //Firebase
    implementation "com.google.firebase:firebase-core:$rootProject.playServiceVersion"
    implementation "com.google.firebase:firebase-config:$rootProject.playServiceVersion"
    //implementation "com.google.firebase:firebase-crash:$rootProject.playServiceVersion"
    implementation "com.google.firebase:firebase-messaging:$rootProject.playServiceVersion"
    implementation "com.google.firebase:firebase-invites:$rootProject.playServiceVersion"
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.2'

    implementation "com.google.android.gms:play-services-auth:$rootProject.playServiceVersion"

    //Facebook
    implementation 'com.facebook.android:facebook-login:[4,5)'
    implementation 'com.facebook.android:account-kit-sdk:4.24.0'
    implementation 'com.facebook.fresco:fresco:1.9.0'

    //Font
    implementation "uk.co.chrisjenx:calligraphy:$rootProject.calligraphyVersion"

    //Network
    implementation "com.amitshekhar.android:rx2-android-networking:$rootProject.rx2FastAndroidNetworking"

    //Image
    implementation "com.squareup.picasso:picasso:$rootProject.picassoVersion"
    //For picasso caching dependency
    implementation 'com.squareup.okhttp3:okhttp:3.9.1'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.+'

    //For MoneyTextView
    implementation 'org.fabiomsr:moneytextview:1.0.3'

    //For runtime permission
    implementation 'com.github.tajchert:nammu:1.2.0'

    // debug database
    debugCompile "com.amitshekhar.android:debug-db:$rootProject.debugDBVersion"

    // view pager dot indicator
    compile 'me.relex:circleindicator:1.2.2@aar'
    // for recycler view scrolling
    compile 'com.github.takusemba:multisnaprecyclerview:1.1.1'

    //Code generator for view
    implementation "com.jakewharton:butterknife:$rootProject.butterKnifeVersion"
    annotationProcessor "com.jakewharton:butterknife-compiler:$rootProject.butterKnifeVersion"

    //To maintain instance state

    //compile 'frankiesardo:icepick:3.2.0'

    //provided 'frankiesardo:icepick-processor:3.2.0'
    api 'frankiesardo:icepick:3.2.0'
    compileOnly 'frankiesardo:icepick-processor:3.2.0'
    annotationProcessor 'frankiesardo:icepick-processor:3.2.0'

    //Circular imageView
    implementation 'de.hdodenhof:circleimageview:2.2.0'


    //Tooltip
    implementation 'com.github.vihtarb:tooltip:0.1.9'

    //Material Dialog
    implementation 'com.afollestad.material-dialogs:commons:0.9.3.0'

    //Image cropping
    implementation 'com.github.yalantis:ucrop:2.2.1-native'


    //Image compression library
    implementation 'id.zelory:compressor:2.1.0'

    //Razor pay
    implementation 'com.razorpay:checkout:1.4.1'

    //For photo filter sdk
    implementation 'com.github.zomato:androidphotofilters:1.0.1'

    // dependencies for local unit tests
    testCompile "junit:junit:$rootProject.ext.junitVersion"

    //Linkedin profile mentions
    implementation 'com.linkedin.android.spyglass:spyglass:1.4.0'


    //For Socket IO
    compile('io.socket:socket.io-client:1.0.0') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }

    //showcase library
    implementation 'com.github.wooplr:Spotlight:1.2.3'

    implementation 'com.github.glomadrian:Grav:1.1'
    implementation 'nl.dionsegijn:konfetti:1.1.2'
    implementation 'com.github.MatteoBattilana:WeatherView:2.0.3'
    implementation 'com.plattysoft.leonids:LeonidsLib:1.3.2'


    //For video/Gif creation
    implementation 'com.writingminds:FFmpegAndroid:0.3.2'
    }
